name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive production artifacts
        run: tar -czf dist.tar.gz -C dist .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist.tar.gz
          
      - name: Verify build artifacts
        run: ls -la

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add server to known hosts
        run: ssh-keyscan 95.216.252.50 >> ~/.ssh/known_hosts

      - name: Refresh directory
        run: |
          ssh tucanoweb@95.216.252.50 <<EOF
          rm -rf crip-decrip-app
          EOF

      - name: Copy files to server
        run: |
          scp -r dist.tar.gz tucanoweb@95.216.252.50:/home/tucanoweb/crip-decrip-app

      - name: Deploy to Kubernetes
        run: |
          ssh tucanoweb@95.216.252.50 <<EOF
          cd crip-decrip-app
          ls -la
          tar -xf dist.tar.gz
          microk8s kubectl create namespace httpd-namespace-devops || true
          microk8s kubectl apply -f - <<EOFYAML
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: crip-decrip-pv
          spec:
            capacity:
              storage: 1Gi
            accessModes:
              - ReadWriteOnce
            hostPath:
              path: /home/tucanoweb/crip-decrip-app
          ---
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: crip-decrip-pvc
            labels:
              app: crip-decript-app
            namespace: httpd-namespace-devops
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            volumeName: crip-decrip-pv
          ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: crip-decrip-app
            labels:
              app: crip-decrip-app
            namespace: httpd-namespace-devops
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: crip-decrip-app
                tier: frontend
            strategy:
              type: Recreate
            template:
              metadata:
                labels:
                  app: crip-decrip-app
                  tier: frontend
              spec:
                containers:
                - name: crip-decrip-app
                  image: nginx:latest
                  ports:
                  - containerPort: 80
                    name: crip-decrip-app
                  volumeMounts:
                  - name: app-volume
                    mountPath: /usr/share/nginx/html
                volumes:
                - name: app-volume
                  persistentVolumeClaim:
                    claimName: crip-decrip-pvc
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: crip-decrip-app
            namespace: httpd-namespace-devops
          spec:
            ports:
            - protocol: TCP
              port: 80
              targetPort: 80
            selector:
              app: crip-decrip-app
              tier: frontend
            type: LoadBalancer
          ---
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: crip-decrip-app-ingress
            namespace: httpd-namespace-devops
          spec:
            rules:
            - http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: crip-decrip-app
                      port:
                        number: 80
          EOFYAML
          POD_NAME=$(kubectl get pods -n httpd-namespace-devops -l app=crip-decrip-app -o jsonpath='{.items[0].metadata.name}')
          cd /home/tucanoweb/crip-decrip-app
          microk8s kubectl cp -n httpd-namespace-devops . $POD_NAME:/usr/share/nginx/html
          EOF
